[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D CORE_DEBUG_LEVEL=0

lib_deps =
  mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display @ ^3.0.9
  bblanchon/ArduinoJson @ ^7.0.4
  me-no-dev/ESP Async WebServer @ ^1.2.4
  me-no-dev/AsyncTCP @ ^1.1.1

board_build.filesystem = littlefs
